/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const computed: typeof import('vue').computed
  const defineStore: typeof import('pinia').defineStore
  const onMounted: typeof import('vue').onMounted
  const reactive: typeof import('vue').reactive
  const ref: typeof import('vue').ref
  const useDark: typeof import('@vueuse/core').useDark
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useStorage: typeof import('@vueuse/core').useStorage
  const useToggle: typeof import('@vueuse/core').useToggle
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly useDark: UnwrapRef<typeof import('@vueuse/core')['useDark']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useStorage: UnwrapRef<typeof import('@vueuse/core')['useStorage']>
    readonly useToggle: UnwrapRef<typeof import('@vueuse/core')['useToggle']>
  }
}