/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NavItem: typeof import('./components/layout/nav-item/nav-item.vue')['default']
    NotificationItem: typeof import('./components/layout/notifications/notification-item.vue')['default']
    Notifications: typeof import('./components/layout/notifications/index.vue')['default']
    NotificationsEmptyState: typeof import('./components/layout/notifications/notifications-empty-state.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./components/layout/search/SearchDialog.vue')['default']
    SidebarNav: typeof import('./components/nav/SidebarNav.vue')['default']
    SidebarNavItem: typeof import('./components/nav/SidebarNavItem.vue')['default']
    TopBar: typeof import('./components/topbar/TopBar.vue')['default']
  }
}
